CREATE TABLE `users` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `firstName` varchar(255) default NULL,
  `lastName` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Xenos","Reilly","at.egestas.a@diamProindolor.co.uk"),("Alan","Mooney","sagittis.Duis@nisimagna.com"),("Nolan","Bishop","ac.libero@necdiam.edu"),("Emery","Wheeler","cursus.in.hendrerit@diam.edu"),("Mason","Curry","at@ut.ca"),("Dara","Schneider","sem@idsapienCras.co.uk"),("Kiona","Buckner","eu.elit@aliquet.org"),("Daphne","Craig","augue.id.ante@nec.edu"),("Clarke","Curry","convallis.ligula.Donec@ac.com"),("Vivien","Cote","tempus@at.net");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Harper","Raymond","Quisque@luctusipsum.org"),("Kirestin","Phillips","magna.Cras.convallis@indolorFusce.ca"),("Kelsey","Cabrera","Quisque.ac@sapien.edu"),("Kyle","Shannon","tortor.Integer@purus.net"),("Skyler","Chang","In.nec.orci@cursusnon.co.uk"),("Zachary","Stevenson","Maecenas.ornare.egestas@CurabiturdictumPhasellus.com"),("Pascale","Carr","fermentum.fermentum.arcu@pellentesquemassalobortis.com"),("Ruth","Jones","Nunc.lectus.pede@nequetellusimperdiet.edu"),("Zelenia","Justice","scelerisque.neque.Nullam@Inornare.ca"),("Nathan","Hudson","vitae.diam.Proin@tempordiamdictum.org");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Connor","Bell","mi.lacinia.mattis@euismodest.ca"),("Alana","Robinson","cursus.purus@nibhenim.com"),("Amery","Sampson","est.Nunc@inconsequat.co.uk"),("Christian","Callahan","purus.accumsan.interdum@Sed.edu"),("Nero","Koch","adipiscing.fringilla@sagittissemperNam.org"),("Fletcher","Rush","vitae.mauris@Aliquam.edu"),("Harlan","Levy","eros@inceptos.ca"),("Lareina","Price","quis.urna@mauriserateget.co.uk"),("Benjamin","Sampson","Phasellus.dapibus@Donec.com"),("Shay","Mcdowell","Quisque.purus.sapien@dignissimtempor.co.uk");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Alfreda","Horn","porta.elit@Vestibulum.net"),("Brennan","Kramer","ornare@a.org"),("Dahlia","Mclean","ipsum.sodales@sociis.net"),("Kirby","Shaffer","scelerisque.neque@tinciduntnunc.com"),("Phillip","Cherry","molestie.dapibus.ligula@nonmagna.co.uk"),("Jamalia","Cooke","netus@Duissit.ca"),("Jaime","Gray","nec.ante@tempuseuligula.com"),("Colt","Mathis","urna.Nullam.lobortis@montesnasceturridiculus.co.uk"),("Kathleen","Patrick","ullamcorper@arcu.net"),("Molly","Santana","hymenaeos@neceuismod.ca");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Drake","Nixon","lacinia.vitae.sodales@Aliquamadipiscinglobortis.org"),("Chava","Walls","massa.lobortis.ultrices@enimnislelementum.net"),("Abra","Morris","Mauris.blandit.enim@Maurismolestiepharetra.com"),("Chantale","Dodson","erat@convalliserat.org"),("Hilel","Medina","rhoncus.Proin@feugiatnecdiam.com"),("Jordan","Santos","volutpat.Nulla.dignissim@vitaesodalesnisi.org"),("Sloane","Mooney","justo.Praesent.luctus@feugiatSednec.co.uk"),("Taylor","Melton","quam@iaculisaliquet.net"),("Thaddeus","Quinn","Morbi@sociisnatoquepenatibus.edu"),("Walter","Singleton","tempor.erat.neque@semsemper.com");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Lesley","Morrison","ipsum@consequatenimdiam.org"),("Henry","Salas","Donec@enimSuspendissealiquet.net"),("Maggie","Scott","Donec.vitae@ligulaNullam.ca"),("Jelani","Marquez","lectus@cursusvestibulumMauris.com"),("Cherokee","Mooney","orci.lacus.vestibulum@non.com"),("Richard","Kirby","nibh.Quisque.nonummy@ipsumdolor.org"),("Allen","Bauer","amet@tellusimperdiet.ca"),("Cyrus","Bryan","neque@sollicitudincommodo.co.uk"),("Clinton","Barrett","Fusce.diam.nunc@habitantmorbi.edu"),("Kelly","Torres","nunc.In@nisi.co.uk");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Marcia","Hobbs","facilisi.Sed.neque@Nunccommodo.ca"),("Denise","Solis","Quisque.fringilla@Morbi.net"),("Bethany","Mann","ipsum.cursus@imperdietdictummagna.edu"),("Hamilton","Mccormick","varius.Nam.porttitor@molestietellus.ca"),("Tarik","Dunn","Donec.felis@maurisipsum.co.uk"),("Jason","Charles","elit.a@pedenec.co.uk"),("Kirsten","Alvarez","arcu.Nunc.mauris@purusDuis.net"),("Brooke","Gill","nec.metus.facilisis@pedeCumsociis.net"),("Alana","Carney","dui.Suspendisse@ante.org"),("Chloe","Manning","quis@ultriciessem.org");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Ferdinand","Franco","ante@diam.org"),("Germaine","Hurst","dui.in.sodales@justoeu.ca"),("Ruth","Hood","mauris@semsemper.edu"),("Fiona","Leach","accumsan.neque@parturientmontesnascetur.edu"),("Keane","Holland","pede.malesuada.vel@eleifendCras.edu"),("Kalia","Walker","dis.parturient@nibh.org"),("Ferdinand","Ochoa","nascetur.ridiculus@sit.com"),("Amal","Monroe","sagittis.Duis.gravida@orciquis.co.uk"),("Ralph","Frost","ornare.lectus.justo@anteVivamus.co.uk"),("Hilel","Crosby","faucibus.orci@amet.ca");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Florence","Le","sed.dui@Nulla.ca"),("Dolan","Mclaughlin","sem@mattisIntegereu.edu"),("Willa","Vargas","purus.Maecenas.libero@amet.org"),("Glenna","Cox","quis.diam.Pellentesque@Nam.net"),("Dahlia","Malone","vitae.sodales.at@magnis.com"),("Ashely","Owens","dictum.eu.placerat@a.edu"),("Shea","Slater","Vivamus.molestie.dapibus@vestibulummassarutrum.org"),("Tanisha","Acevedo","dolor@elit.net"),("Emery","Landry","congue@magnaCras.org"),("Geraldine","Lang","semper@fringillaporttitorvulputate.com");
INSERT INTO `users` (`firstName`,`lastName`,`email`) VALUES ("Haviva","Wynn","tristique@Donec.com"),("Carol","Mckenzie","nec@mollis.edu"),("Uriel","Blevins","nec.orci.Donec@Suspendisse.co.uk"),("Cade","Hudson","gravida.nunc.sed@Proin.ca"),("Carl","Miranda","non.dapibus@semperNam.org"),("Ian","Mckenzie","eu@sitamet.edu"),("Emery","Tyson","orci.Ut.semper@ornaretortorat.edu"),("Gay","Farrell","dictum.magna.Ut@Cras.co.uk"),("Elliott","Meyer","iaculis.quis.pede@tellus.net"),("Abbot","Dawson","lobortis.tellus@bibendumsedest.ca");
